### ISSUE TITLE
Chart Template is invalid. DaemonSet Invalid

### ISSUE THREAD

**Issue by DandyDeveloper** [cirocosta/dmesg_exporter#1]
Hey @cirocosta 

I've actually made a branch to fix this and add some things to the helm chart. Any way I can contribute to this? 

I can drop a PR for you to review.

**Comment by cirocosta** [comment]
Hi @DandyDeveloper ,

Thanks for the issue, and, yeahh, please PR it in 😁  happy to review it!

Thanks!

**Comment by DandyDeveloper** [comment]
@cirocosta I think you need to add me as a contrib. I can't push my branch.

Thank you for getting back to me!

**Comment by cirocosta** [comment]
Hi @DandyDeveloper ,

oh that's actually not needed - you can instead:

1. fork the repository (e.g., to `DandyDeveloper/dmesg_exporter`)
2. push the code to a branch in your fork (e.g., `fix-daemonset`)
3. create a PR to this repository

(see https://help.github.com/en/articles/creating-a-pull-request-from-a-fork)

Hope that helps 😁

**Comment by DandyDeveloper** [comment]
@cirocosta Weirdly the daemonset isn't complaining anymore so I'm going to just close this. I think my indentation was bad when I added some extra params from my local clone.

If I do find anything though, I'll do the above. 

One thing to note: Was there a specific reason you only fetch fidelity and priority, even though the struct contains several other useful properties?

**Comment by cirocosta** [comment]
Oh, cool!

No specific reason actually - I started with the fields that I found that would be useful for me right away, and then went with those (as I didn't need anything else) 👍
